### ISSUE TITLE
New branch created "Huge Update"

### ISSUE THREAD

**Issue by challsted** [challsted/masammich#18]
Huge Update is incoming, this issue will be closed when its completed. 

*No longer trying to use themes, the dark theme looks good. 
*Adding a shell scripting "lesson plan" for noobies, thats the biggest request im getting and what i have isnt helping as much as i planned.
    \* Created new folder, and moving some pages around, will need to bug check for broken links
    \* Adding a new dynamic page to the top of each of these pages, this new page is a ordered list that lists the pages of the lessons, currently at the top of each page
    \* Need to add arrows at the bottom of each lesson to go forward or backward
*Plan to make "end of lesson" pages have some javascript functionality to click and highlight if correct or wrong. Maybe add a popup of why its wrong?
    \* This will not hold back the push, its a planned feature

Once this is closed, and tested, push the site forward to 2.0

**Comment by hackinginformation** [comment]
Most of what was requested in this issue has been completed and fixed.
