### ISSUE TITLE
severed.technoanomaly.com - Huge Failure

### ISSUE THREAD

**Issue by challsted** [challsted/masammich#19]
Not sure whats going on yet, but something is very wrong with the layout. 

Mobile is getting double headers (1 white and 1 black)
On my firefox i getting a double height header, and all of the new pages are not pulling the content in. 

Created new branch and checked out at local "recombine" 
Going to attempt to put the content and html files back together (like master has) to see if that fixes it.

**Comment by hackinginformation** [comment]
Had to start over from the begining with a fresh pull. It is now a success and is much further then this issue.
